import type { Metadata } from "next";
import "./styles/globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "Threads",
  description: "Generated by create next app",
  icons: {
    icon: "https://static.cdninstagram.com/rsrc.php/ye/r/lEu8iVizmNW.ico", // URL del favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"background-2 antialiased"}
     >
        <SpeedInsights/>
        {children}
      </body>
    </html>
  );
}
