import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Buscar - Threads",
  description: "Generated by create next app",
};

export default function SearchLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
