import type { Metadata } from "next";
import "@/app/styles/globals.css";

export const metadata: Metadata = {
  title: "Buscar • Threads",
  description: "Generated by create next app",
};

export default function SearchLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)  {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
